clear;clc;
strname='Multi_AID_Rcn';
load '..\ClassifierResult\Multi_AID_Classifier_PR.mat';
FeaturesPR=Multi_MvFLRS_AID_PR;
boxplot(FeaturesPR.Accuracy,FeaturesPR.MethodNames);
title('The results of the AID Classification');
xlabel('Methods');
ylabel('Accuracy');
strpr1=sprintf('%s%s%s','.\FiguresAndDatas\',strname,'PR.fig');
saveas(gcf,strpr1);
RcnPR.mean=mean(FeaturesPR.Accuracy);
RcnPR.Max=max(FeaturesPR.Accuracy);
RcnPR.MethodsName=FeaturesPR.MethodNames;
save('.\FiguresAndDatas\Multi_AID_RcnPR.mat','RcnPR');