clear;clc;
strname='WHU_V3';
load '..\ClassifierResult\WHU_CV3_PR.mat';
FeaturesPR=MvFLRS_WHU_PR;
boxplot(FeaturesPR.Accuracy,FeaturesPR.MethodNames);
title('The results of the WHU Classification with 3 views feature');
xlabel('Methods');
ylabel('Accuracy');
strpr1=sprintf('%s%s%s','.\FiguresAndDatas\',strname,'PR.fig');
saveas(gcf,strpr1);
RcnPR.mean=mean(FeaturesPR.Accuracy);
RcnPR.Max=max(FeaturesPR.Accuracy);
RcnPR.MethodsName=FeaturesPR.MethodNames;
save('.\FiguresAndDatas\WHU_V3PR.mat','RcnPR');